name: Build and Release Argus

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build-linux:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Make Linux Build Script Executable
        run: chmod +x ./scripts/build_linux.sh

      - name: Run Linux Build Script
        run: ./scripts/build_linux.sh

      - name: Check Built Files
        run: ls -R ./dist

      - name: Upload Linux Binary to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/Argus
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  build-macos:
    name: Build on macOS
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Make macOS Build Script Executable
        run: chmod +x ./scripts/build_mac.sh

      - name: Run macOS Build Script
        run: ./scripts/build_mac.sh

      - name: Check Built Files
        run: ls -R ./dist

      - name: Upload macOS Binary to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/Argus
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build on Windows
        run: ./scripts/build_win.bat

      - name: List build output
        run: ls -R ./dist

      - name: Upload Windows binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/Argus.exe  # Adjust path
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
