name: Build and Release Argus

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build Executable
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            chmod +x ./scripts/build_linux.sh
            ./scripts/build_linux.sh
          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            chmod +x ./scripts/build_mac.sh
            ./scripts/build_mac.sh
          elif [[ "$RUNNER_OS" == "Windows" ]]; then
            ./scripts/build_win.bat
          fi

      - name: Upload Release Artifact
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
